# Generated by Django 5.1 on 2024-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
